theme: jekyll-theme-minimal
title: Vincent Jeanselme
description: Research Analyst and Programmer at Carnegie Mellon University
logo: https://avatars2.githubusercontent.com/u/16624195?s=460&v=4
show_downloads: "false"